"use strict";
const content = document.getElementById("content");
const esc = value => String(value ?? "").replace(/[&<>\"]/g, char => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[char]));
const places = {home:"Home office",rack:"Home rack",office:"Office",cloud:"On the internet"};
const stateClass = check => check.status === "DOWN" ? (check.alert ? "down" : "away") : check.status === "UP" ? "up" : "unknown";
const kindLabel = {http:"Web page answers",tcp:"Port open",ping:"Host reachable",beat:"Scheduled job ran"};
let data = {checks:[],incidents:[],ledger:[],history:{hours:[],checks:[]},settings:[]};

async function api(path, options) {
  const response = await fetch(path, options);
  const value = await response.json();
  if (!response.ok) throw new Error(value.error || `Request failed (${response.status})`);
  return value;
}
function route() { const name = location.pathname.slice(1); return ["now","registry","rules","reporting","assignment","timeline","history","settings"].includes(name) ? name : "now"; }
function toast(message) { const el = document.querySelector(".toast"); el.textContent = message; el.classList.add("show"); setTimeout(() => el.classList.remove("show"), 2600); }
function setNav(name) { document.querySelectorAll("[data-route]").forEach(link => link.toggleAttribute("aria-current", link.dataset.route === name)); }
function targetText(check) { const target=check.target || {}; return target.url || (target.port ? `${target.host}:${target.port}` : target.host || target.job || JSON.stringify(target)); }
function lastText(value) { if (!value) return "waiting for first check"; const date=new Date(value); return Number.isNaN(date.valueOf()) ? value : date.toLocaleString([], {dateStyle:"medium",timeStyle:"short"}); }
function sinceText(value) { const date=new Date(value); if(Number.isNaN(date.valueOf()))return `Since ${value}`;const minutes=Math.max(0,Math.floor((Date.now()-date.valueOf())/60000));const time=new Intl.DateTimeFormat("en-US",{hour:"numeric",minute:"2-digit"}).format(date);const day=new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric"}).format(date);return `Since ${time}, ${day} (${minutes<1?"just now":`${minutes} min ago`})`; }
function counts(checks=data.checks) { return checks.reduce((total,check)=>{total[stateClass(check)]++;return total;},{down:0,up:0,away:0,unknown:0}); }
function checkSummary(check) { return check.kind === "beat" && !check.last_at ? "Waiting for its first run" : `${kindLabel[check.kind] || check.kind} · ${lastText(check.last_at)}`; }

function headerSummary() {
  const total=counts();
  document.getElementById("watcher").innerHTML=`The watcher is tracking <b>${data.checks.length}</b> checks. ${total.down ? `<span class="error"><b>${total.down}</b> need attention.</span>` : "Nothing is down."}`;
}
function node(check) {
  const model=check.kind==="http" && String(check.target?.url||"").endsWith("/device.json");
  return `<article class="node ${stateClass(check)}${model?" model":""}"><i class="pin" aria-hidden="true"></i><b>${esc(check.display_name)}</b><small>${esc(checkSummary(check))}</small>${model?'<div class="lane"><b>Idle</b><i></i><i></i><i></i><span>0 waiting</span></div>':""}</article>`;
}
function zone(place) {
  const checks=data.checks.filter(check => check.place===place); const total=counts(checks);
  const rows=place==="rack"?`<div class="rack">${checks.map(check=>`<div class="ru ${stateClass(check)}"><i></i><b>${esc(check.display_name)}</b><span>${esc(checkSummary(check))}</span></div>`).join("")}</div>`:`<div class="nodes">${checks.map(node).join("")}</div>`;
  const summary=checks.length ? [`${total.up} fine`,total.down?`${total.down} down`:"",total.away?`${total.away} away`:"",total.unknown?`${total.unknown} waiting`:""].filter(Boolean).join(", ") : "No checks yet";
  return `<section class="zone z-${place}${total.down?" hot":""}"><div class="zh"><h2>${places[place]}</h2><p class="${total.down?"bad":""}">${summary}</p></div>${rows}</section>`;
}
function incidentCard() {
  if (!data.incidents.length) return `<section class="call clear"><h1>All clear</h1><ol class="five"><li data-line="1">No open incidents.</li><li data-line="2">Checks keep running on their own schedule.</li><li data-line="3">Single misses stay in the Timeline.</li><li data-line="4">Add anything missing from Registry.</li><li data-line="5">The History tab keeps the 36 hour view.</li></ol></section>`;
  const incident=data.incidents[0],lines=[...(incident.five_lines||[])];
  if(lines[1])lines[1]=`${sinceText(incident.opened_at)}. ${lines[1].replace(/^Since .*?\. /,"")}`;
  return `<section class="call"><h1><span class="line-no">1</span>${esc(lines[0])}</h1><ol class="five">${lines.slice(1).map((line,index)=>`<li data-line="${index+2}">${esc(line)}</li>`).join("")}</ol></section>`;
}
function now() {
  const tally=counts();
  content.innerHTML=`<div class="layout"><div class="plan">${incidentCard()}${zone("home")}${zone("rack")}${zone("office")}${zone("cloud")}</div><aside class="aside"><section class="box"><h2>Right now</h2><div class="tally"><div><b class="bad">${tally.down}</b><span>down</span></div><div><b>${tally.up}</b><span>fine</span></div><div><b>${tally.away}</b><span>away</span></div><div class="wait"><b>${tally.unknown}</b><span>waiting</span></div></div></section><section class="box"><h2>The Tiiny's lane</h2><p><b>Idle</b>, 0 waiting. One answer at a time.</p><p class="muted">Rules keep watching even when the model is unavailable.</p></section><section class="box"><h2>Reading the plan</h2><div class="legend"><span><i></i>Up</span><span><i class="bad"></i>Down, someone was told</span><span><i class="away"></i>Away, logged only</span><span><i class="wait"></i>Waiting for a first result</span></div></section></aside></div>`;
}
function detect(raw) {
  const value=raw.trim(); if(!value) return null;
  if(/^https?:\/\//i.test(value)) { try { const url=new URL(value); return {kind:"http",name:url.hostname.replace(/^www\./,""),place:"cloud",note:"A web page on the internet. It must answer successfully."}; } catch { return {error:"That web address has a typo."}; } }
  if(/^[\w.-]+:\d+$/.test(value)) return {kind:"tcp",name:value,place:"home",note:"A host and port. It must accept a connection."};
  if(/^[\w.-]+$/.test(value)) return {kind:"ping",name:value,place:/^(10\.|192\.168\.|100\.)/.test(value)?"home":"cloud",note:"A host. It must answer on the network."};
  return {error:"Paste a web address, host name, address, or host and port."};
}
function registry() {
  content.innerHTML=`<div class="page"><div class="wiz"><form class="steps" id="registry"><div class="step"><p class="num">1</p><div><h2><label for="target">What should it watch?</label></h2><input class="big-in" id="target" name="target" placeholder="https://example.com/health or server:443" required><p class="detect"></p><input type="hidden" name="kind"></div></div><div class="step"><p class="num">2</p><fieldset><legend><h2>Where is it?</h2></legend><div class="cards">${Object.entries(places).map(([key,label],index)=>`<label><input type="radio" name="place" value="${key}" ${index?"":"checked"}><span>${label}</span></label>`).join("")}</div></fieldset></div><div class="step"><p class="num">3</p><fieldset><legend><h2>How loud?</h2></legend><div class="cards">${[["critical","Critical"],["warning","Warning"],["info","Info"],["presence","Presence only"]].map(([key,label],index)=>`<label><input type="radio" name="severity" value="${key}" ${index===1?"checked":""}><span>${label}</span></label>`).join("")}</div></fieldset></div><div class="step"><p class="num">4</p><div><h2>Who, and what first?</h2><div class="pair"><label class="field">Name<input name="display_name" required placeholder="Backup box"></label><label class="field">Owner<input name="owner" required placeholder="Operations lead"></label><label class="field full">Do this first<input name="first_step" required placeholder="Check it has power and is connected"></label><label class="field full">What it likely means<input name="meaning" required placeholder="The service or its network connection stopped"></label></div><div class="form-actions"><button class="btn primary" type="submit">Put it on the plan</button></div></div></div></form><aside class="preview panel"><h2>It lands here</h2><p class="muted">The preview follows your choices.</p><div id="preview"></div></aside></div></div>`;
  const form=document.getElementById("registry"), detectEl=form.querySelector(".detect"), preview=document.getElementById("preview");
  function sync(){const found=detect(form.target.value);detectEl.textContent=found?(found.error||`${kindLabel[found.kind]}. ${found.note}`):"";detectEl.classList.toggle("error",!!found?.error);if(found&&!found.error){form.kind.value=found.kind;if(!form.display_name.value)form.display_name.value=found.name;form.querySelector(`[name=place][value=${found.place}]`).checked=true;}const values=new FormData(form);const place=values.get("place")||"home";preview.innerHTML=`<div class="zone hot"><div class="zh"><h2>${places[place]}</h2></div><div class="node"><i class="pin"></i><b>${esc(values.get("display_name")||"New check")}</b><small>First check within a minute</small></div></div>`;}
  form.addEventListener("input",sync);form.addEventListener("submit",async event=>{event.preventDefault();const values=Object.fromEntries(new FormData(form));const found=detect(values.target);if(!found||found.error){sync();form.target.focus();return;}const id=(values.display_name||found.name).toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,80);try{await api("/api/checks",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...values,id,kind:found.kind,where_text:places[values.place],period_s:60,grace_s:90,misses_before_real:3,cooldown_s:600,alert:values.severity!=="presence"})});await load();history.pushState({},"","/now");render();toast("On the plan. First check within a minute.");}catch(error){toast(error.message);}});sync();
}
function rules() {
  content.innerHTML=`<div class="page"><div class="page-head"><div><h1>Rules</h1><p>What makes a miss real, when to stay quiet, and what the owner does first.</p></div></div><div class="rule-grid">${data.checks.map(check=>`<form class="panel rule" data-rule="${esc(check.id)}"><div class="rule-head"><h2>${esc(check.display_name)}</h2><span class="pill">${esc(kindLabel[check.kind]||check.kind)}</span></div><p class="muted">${esc(targetText(check))}</p><div class="rule-fields"><label class="field">Severity<select name="severity">${["critical","warning","info"].map(value=>`<option ${check.severity===value?"selected":""}>${value}</option>`).join("")}</select></label><label class="field">Real after misses<input name="misses_before_real" type="number" min="1" value="${check.misses_before_real}"></label><label class="field">Check every seconds<input name="period_s" type="number" min="1" value="${check.period_s}"></label><label class="field">Grace seconds<input name="grace_s" type="number" min="0" value="${check.grace_s}"></label><label class="field">Cooldown seconds<input name="cooldown_s" type="number" min="0" value="${check.cooldown_s}"></label><label class="field">Quiet hours<input name="quiet_hours" value="${esc(check.quiet_hours||"")}" placeholder="None"></label><label class="field full">Maintenance windows<input name="maintenance" value="${esc(check.maintenance||"")}" placeholder="None"></label><label class="field full">Verify first<textarea name="playbook">${esc(check.playbook||check.first_step)}</textarea></label></div><div class="form-actions"><button class="btn primary" type="submit">Save rule</button></div></form>`).join("")}</div></div>`;
  content.querySelectorAll("[data-rule]").forEach(form=>form.addEventListener("submit",async event=>{event.preventDefault();const check=data.checks.find(item=>item.id===form.dataset.rule);const values=Object.fromEntries(new FormData(form));const payload={...check,...values,period_s:Number(values.period_s),grace_s:Number(values.grace_s),misses_before_real:Number(values.misses_before_real),cooldown_s:Number(values.cooldown_s)};try{await api("/api/checks",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});await load();rules();toast("Rule saved.");}catch(error){toast(error.message);}}));
}
function readOnly(kind) {
 const isReporting=kind==="reporting";
 content.innerHTML=`<div class="page"><div class="page-head"><div><h1>${isReporting?"Reporting":"Assignment"}</h1><p>${isReporting?"Who hears about a real incident, on which surviving path, and in plain words.":"Which owner receives a verified problem and its first plan."}</p></div></div><section class="panel"><div class="readonly"><b>Read-only in stage 1</b><p>${isReporting?"The Alerts view receives state changes. Additional signal paths appear here as they are configured.":"Ownership follows each Registry entry. Routing changes become editable after verified hand-offs are enabled."}</p></div><div class="rule-grid spaced">${data.checks.map(check=>`<article class="rule"><h2>${esc(check.display_name)}</h2><p><b>${esc(check.owner||"Unassigned")}</b></p><p class="muted">${esc(check.failure_class||"configured check")} · ${esc(check.severity)}</p></article>`).join("")}</div></section></div>`;
}
function timeline() {
  content.innerHTML=`<div class="page"><div class="page-head"><div><h1>Timeline and ledger</h1><p>Append-only. Every incident from first observation through verified close.</p></div></div><div class="timeline">${data.ledger.length?data.ledger.map(row=>`<article class="event"><time>${esc(lastText(row.at))}</time><span class="kind ${esc(row.kind)}">${esc(row.kind)}</span><div><b>${esc(row.actor)}</b><p class="muted">${esc(JSON.stringify(row.body))}</p></div></article>`).join(""):'<div class="empty">No incident events yet. The watcher is still collecting observations.</div>'}</div></div>`;
}
function historyView() {
  const checks=data.history.checks||[];
  content.innerHTML=`<div class="page"><div class="page-head"><div><h1>36 hour history</h1><p>One strip per check. Green answered, amber missed, and an empty square has no observation.</p></div></div><div class="table-wrap"><table class="history"><thead><tr><th>State</th><th>Check</th><th>Last 36 hours</th><th>Last seen</th></tr></thead><tbody>${checks.map(check=>`<tr><td><span class="state ${stateClass(check)}">${esc(check.status)}</span></td><td><b>${esc(check.display_name)}</b><br><small class="muted">${esc(kindLabel[check.kind]||check.kind)}</small></td><td><span class="strip" role="img" aria-label="36 hour observation strip">${check.history.map((state,index)=>`<i class="${state}" title="${esc(data.history.hours[index])}: ${state}"></i>`).join("")}</span></td><td>${esc(lastText(check.last_at))}</td></tr>`).join("")}</tbody></table></div></div>`;
}
function settings() {
  content.innerHTML=`<div class="page"><div class="page-head"><div><h1>Settings</h1><p>Source connections live here. Secrets are write-only and stored in a protected file under the app's data folder.</p></div></div><form class="panel settings" id="settings-form">${data.settings.length?`<div class="setting-group">${data.settings.map(item=>`<label class="field">${esc(item.label)}${item.secret&&item.configured?' <span class="pill">configured</span>':""}<input name="${esc(item.key)}" type="${item.secret?"password":"text"}" value="${esc(item.value||"")}" placeholder="${item.secret&&item.configured?"Leave blank to keep the saved value":""}" autocomplete="off"><span class="setting-help">${esc(item.help||"")}</span></label>`).join("")}</div><button class="btn primary" type="submit">Save settings</button>`:'<div class="empty">No source-specific settings are installed yet. New source modules appear here automatically.</div>'}</form></div>`;
  const form=document.getElementById("settings-form");form.addEventListener("submit",async event=>{event.preventDefault();try{const values=Object.fromEntries(new FormData(form));const result=await api("/api/settings",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(values)});data.settings=result.settings;settings();toast("Settings saved.");}catch(error){toast(error.message);}});
}
function render() { const name=route();setNav(name);({now,registry,rules,reporting:()=>readOnly("reporting"),assignment:()=>readOnly("assignment"),timeline,history:historyView,settings}[name]||now)();content.focus({preventScroll:true}); }
async function load() { const [checks,incidents,ledger,history,settingsValue]=await Promise.all([api("/api/checks"),api("/api/incidents"),api("/api/ledger"),api("/api/history"),api("/api/settings")]);data={checks:checks.checks,incidents:incidents.incidents,ledger:ledger.ledger,history,settings:settingsValue.settings};headerSummary(); }
document.addEventListener("click",event=>{const link=event.target.closest("a[data-route]");if(!link)return;event.preventDefault();history.pushState({},"",link.href);render();});
addEventListener("popstate",render);
const themeButton=document.querySelector(".theme");const systemTheme=matchMedia("(prefers-color-scheme: light)");const requestedTheme=new URLSearchParams(location.search).get("theme");let themeOverride=["light","dark"].includes(requestedTheme)?requestedTheme:localStorage.getItem("tiinyengineer-theme");function applyTheme(theme,remember=false){document.documentElement.dataset.theme=theme;themeButton.textContent=theme==="dark"?"Light":"Dark";themeButton.setAttribute("aria-label",`Use ${theme==="dark"?"light":"dark"} theme`);if(remember){themeOverride=theme;localStorage.setItem("tiinyengineer-theme",theme);}}themeButton.addEventListener("click",()=>applyTheme(document.documentElement.dataset.theme==="dark"?"light":"dark",true));systemTheme.addEventListener("change",event=>{if(!themeOverride)applyTheme(event.matches?"light":"dark");});applyTheme(themeOverride||(systemTheme.matches?"light":"dark"));
load().then(render).catch(error=>{content.innerHTML=`<div class="page"><div class="empty error">The dashboard could not load: ${esc(error.message)}</div></div>`;});
